version: '3.7'
volumes:
        prometheus_data: {}
        grafana_data: {}
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
  node-exporter:
    image: prom/node-exporter
    ports:
      - 9100:9100

  grafana:
    image: grafana/grafana
    user: "1000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=nguyennam16214@gmail.com
      - GF_SMTP_PASSWORD=P@ssWord123
      - GF_SMTP_SKIP_VERIFY=true
      - GF_SMTP_FROM_ADDRESS=nguyennam16214@gmail.com
      - GF_RENDERING_SERVER_URL=http://renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana

  renderer:
    image: grafana/grafana-image-renderer:latest
    ports:
      - 8081
    environment:
      - ENABLE_METRICS= 'true'

